/**
 * build_theme.mjs — Generate theme CSS from a JSON palette config.
 *
 * Usage:
 *   node scripts/build_theme.mjs < content/themes/blue.json
 *   node scripts/build_theme.mjs content/themes/blue.json
 *
 * Reads a theme JSON file (or stdin), outputs a CSS file to stdout
 * that can be saved to dist/themes/{name}.css.
 */

import { readFileSync } from "node:fs";

const input = process.argv[2]
  ? readFileSync(process.argv[2], "utf-8")
  : readFileSync("/dev/stdin", "utf-8");

const theme = JSON.parse(input);
const h = theme.hue;
const dk = theme.dark;
const lt = theme.light;
const glow = theme.aboutGlow;

const css = `/* Theme: ${theme.name} — ${theme.label} */
/* ${theme.description} */
/* Auto-generated by scripts/build_theme.mjs — do not edit manually */

:root {
  /* Hue config */
  --_hue: ${h.primary};
  --_hue-link: ${h.link};
  --_hue-warn: ${h.warn};
  --_hue-error: ${h.error};

  /* Dark mode accent colors */
  --acid:   hsl(var(--_hue), ${dk.acid.s}%, ${dk.acid.l}%);
  --cyan:   hsl(var(--_hue-link), ${dk.cyan.s}%, ${dk.cyan.l}%);
  --amber:  hsl(var(--_hue-warn), ${dk.amber.s}%, ${dk.amber.l}%);
  --red:    hsl(var(--_hue-error), ${dk.red.s}%, ${dk.red.l}%);

  /* About-link glow (RGB derived from accent) */
  --about-glow-r: ${glow.dark.r};
  --about-glow-g: ${glow.dark.g};
  --about-glow-b: ${glow.dark.b};

  /* Accent-tinted surfaces (dark mode) */
  --_accent-glow: rgba(${glow.dark.r}, ${glow.dark.g}, ${glow.dark.b}, .25);

  /* Text on accent backgrounds */
  --brand-accent-text: ${theme.brandAccentText};
}

/* Light mode accent colors */
:root[data-theme="light"] {
  color-scheme: light;

  --acid:   hsl(var(--_hue), ${lt.acid.s}%, ${lt.acid.l}%);
  --cyan:   hsl(var(--_hue-link), ${lt.cyan.s}%, ${lt.cyan.l}%);
  --amber:  hsl(var(--_hue-warn), ${lt.amber.s}%, ${lt.amber.l}%);
  --red:    hsl(var(--_hue-error), ${lt.red.s}%, ${lt.red.l}%);

  /* About-link glow (light mode) */
  --about-glow-r: ${glow.light.r};
  --about-glow-g: ${glow.light.g};
  --about-glow-b: ${glow.light.b};

  /* Accent-tinted surfaces (light mode) */
  --_accent-glow: rgba(${glow.light.r}, ${glow.light.g}, ${glow.light.b}, .25);

  /* Text on accent backgrounds */
  --brand-accent-text: ${theme.brandAccentTextLight};
}

/* System light mode */
@media (prefers-color-scheme: light) {
  :root {
    --acid:   hsl(var(--_hue), ${lt.acid.s}%, ${lt.acid.l}%);
    --cyan:   hsl(var(--_hue-link), ${lt.cyan.s}%, ${lt.cyan.l}%);
    --amber:  hsl(var(--_hue-warn), ${lt.amber.s}%, ${lt.amber.l}%);
    --red:    hsl(var(--_hue-error), ${lt.red.s}%, ${lt.red.l}%);

    --about-glow-r: ${glow.light.r};
    --about-glow-g: ${glow.light.g};
    --about-glow-b: ${glow.light.b};

    --_accent-glow: rgba(${glow.light.r}, ${glow.light.g}, ${glow.light.b}, .25);

    /* Text on accent backgrounds */
    --brand-accent-text: ${theme.brandAccentTextLight};
  }
}
`;

process.stdout.write(css);
